### ISSUE TITLE
Flight controller

### ISSUE THREAD

**Issue by TalhaIlyas** [grassjelly/gesture_drone#1]
which flight controller you have used,what model it is?

**Comment by grassjelly** [comment]
Naza Lite

**Comment by TalhaIlyas** [comment]
sir schematics are a little unclear,is the range of gesture control is limited to the range of HC-05/06 BT modules or are you controlling the 5-CH transmitter receiver with them?schematics for wearable...isn't clear...!
can you plz share the detailed schematics diagram...it'll be of great help,thanks,

**Comment by RockGeek2301** [comment]
Will this project work in any flight controller

**Comment by gkrbala** [comment]
hello sir schematic are not clear please share the detailed schematics diagram
